import { registerGraph } from "../lib/registry";
import { graph01HelloLanggraph } from "./01-hello-langgraph/index";
import { graph02StateAndAnnotations } from "./02-state-and-annotations/index";
import { graph03StreamingLayer } from "./03-streaming-layer/index";
import { graph04MultiTurnConversations } from "./04-multi-turn-conversations/index";
import { graph05PromptTemplates } from "./05-prompt-templates/index";
import { graph06FewShotPrompting } from "./06-few-shot-prompting/index";
import { graph07TemplateComposition } from "./07-template-composition/index";
import { graph08StructuredOutput } from "./08-structured-output/index";
import { graph09PuttingItTogether } from "./09-putting-it-together/index";
import { graph09ThreadPersistence } from "./09-thread-persistence/index";
import { graph10ContextManagement } from "./10-context-management/index";
import { graph11EmbeddingsSimilarity } from "./11-embeddings-similarity/index";
import { graph12LongTermMemory } from "./12-long-term-memory/index";
import { graph13RagFundamentals } from "./13-rag-fundamentals/index";
import { graph14AdvancedRag } from "./14-advanced-rag/index";
import { graph15DefiningTools } from "./15-defining-tools/index";
import { graph16ReactAgent } from "./16-react-agent/index";
import { graph17Multimodal } from "./17-multimodal/index";
import { graph18HumanInTheLoop } from "./18-human-in-the-loop/index";
import { graph19PromptChaining } from "./19-prompt-chaining/index";
import { graph20Routing } from "./20-routing/index";
import { graph21AdvancedRoutingCommand } from "./21-advanced-routing-command/index";
import { graph22Subgraphs } from "./22-subgraphs/index";
import { graph23ParallelPatterns } from "./23-parallel-patterns/index";
import { graph24OrchestratorWorker } from "./24-orchestrator-worker/index";
import { graph25EvaluatorOptimizer } from "./25-evaluator-optimizer/index";
import { graph26HierarchicalTeams } from "./26-hierarchical-teams/index";
import { graph27SwarmHandoff } from "./27-swarm-handoff/index";
import { graph28McpServer } from "./28-mcp-server/index";
import { graph29GenerativeUiFundamentals } from "./29-generative-ui-fundamentals/index";
import { graph30InteractiveGenerativeUi } from "./30-interactive-generative-ui/index";
import { graph31HumanInTheLoopUi } from "./31-human-in-the-loop-ui/index";
import { graph32LanggraphPlatformUi } from "./32-langgraph-platform-ui/index";
import { graph33DisplayIntents } from "./33-display-intents/index";
import { graph34InteractiveIntents } from "./34-interactive-intents/index";
import { graph35Guardrails } from "./35-guardrails/index";
import { graph36ModelLevelHooks } from "./36-model-level-hooks/index";
import { graph37ErrorHandling } from "./37-error-handling/index";
import { graph38Monitoring } from "./38-monitoring/index";
import { graph39Testing } from "./39-testing/index";
import { graph40EvaluationFramework } from "./40-evaluation-framework/index";
import { graph41Scaling } from "./41-scaling/index";
import { graph42ApplicationStructure } from "./42-application-structure/index";

// Register all 43 graphs
registerGraph(graph01HelloLanggraph);
registerGraph(graph02StateAndAnnotations);
registerGraph(graph03StreamingLayer);
registerGraph(graph04MultiTurnConversations);
registerGraph(graph05PromptTemplates);
registerGraph(graph06FewShotPrompting);
registerGraph(graph07TemplateComposition);
registerGraph(graph08StructuredOutput);
registerGraph(graph09PuttingItTogether);
registerGraph(graph09ThreadPersistence);
registerGraph(graph10ContextManagement);
registerGraph(graph11EmbeddingsSimilarity);
registerGraph(graph12LongTermMemory);
registerGraph(graph13RagFundamentals);
registerGraph(graph14AdvancedRag);
registerGraph(graph15DefiningTools);
registerGraph(graph16ReactAgent);
registerGraph(graph17Multimodal);
registerGraph(graph18HumanInTheLoop);
registerGraph(graph19PromptChaining);
registerGraph(graph20Routing);
registerGraph(graph21AdvancedRoutingCommand);
registerGraph(graph22Subgraphs);
registerGraph(graph23ParallelPatterns);
registerGraph(graph24OrchestratorWorker);
registerGraph(graph25EvaluatorOptimizer);
registerGraph(graph26HierarchicalTeams);
registerGraph(graph27SwarmHandoff);
registerGraph(graph28McpServer);
registerGraph(graph29GenerativeUiFundamentals);
registerGraph(graph30InteractiveGenerativeUi);
registerGraph(graph31HumanInTheLoopUi);
registerGraph(graph32LanggraphPlatformUi);
registerGraph(graph33DisplayIntents);
registerGraph(graph34InteractiveIntents);
registerGraph(graph35Guardrails);
registerGraph(graph36ModelLevelHooks);
registerGraph(graph37ErrorHandling);
registerGraph(graph38Monitoring);
registerGraph(graph39Testing);
registerGraph(graph40EvaluationFramework);
registerGraph(graph41Scaling);
registerGraph(graph42ApplicationStructure);

console.log("All 43 graphs registered successfully");
