import { registerGraph } from "../lib/registry";
import { graph01HelloLanggraph } from "./01-hello-langgraph/index";
import { graph02StateAndAnnotations } from "./02-state-and-annotations/index";
import { graph03MultiTurnConversations } from "./03-multi-turn-conversations/index";
import { graph04PromptTemplates } from "./04-prompt-templates/index";
import { graph05FewShotPrompting } from "./05-few-shot-prompting/index";
import { graph06TemplateComposition } from "./06-template-composition/index";
import { graph07StructuredOutput } from "./07-structured-output/index";
import { graph08PuttingItTogether } from "./08-putting-it-together/index";
import { graph09ThreadPersistence } from "./09-thread-persistence/index";
import { graph10ContextManagement } from "./10-context-management/index";
import { graph11EmbeddingsSimilarity } from "./11-embeddings-similarity/index";
import { graph12LongTermMemory } from "./12-long-term-memory/index";
import { graph13RagFundamentals } from "./13-rag-fundamentals/index";
import { graph14AdvancedRag } from "./14-advanced-rag/index";
import { graph15DefiningTools } from "./15-defining-tools/index";
import { graph16ReactAgent } from "./16-react-agent/index";
import { graph17Multimodal } from "./17-multimodal/index";
import { graph18HumanInTheLoop } from "./18-human-in-the-loop/index";
import { graph19PromptChaining } from "./19-prompt-chaining/index";
import { graph20Routing } from "./20-routing/index";
import { graph21Subgraphs } from "./21-subgraphs/index";
import { graph22ParallelPatterns } from "./22-parallel-patterns/index";
import { graph23OrchestratorWorker } from "./23-orchestrator-worker/index";
import { graph24EvaluatorOptimizer } from "./24-evaluator-optimizer/index";
import { graph25HierarchicalTeams } from "./25-hierarchical-teams/index";
import { graph26GenerativeUiFundamentals } from "./26-generative-ui-fundamentals/index";
import { graph27InteractiveGenerativeUi } from "./27-interactive-generative-ui/index";
import { graph28HumanInTheLoopUi } from "./28-human-in-the-loop-ui/index";
import { graph29LanggraphPlatformUi } from "./29-langgraph-platform-ui/index";
import { graph30DisplayIntents } from "./30-display-intents/index";
import { graph31InteractiveIntents } from "./31-interactive-intents/index";
import { graph32Guardrails } from "./32-guardrails/index";
import { graph33ErrorHandling } from "./33-error-handling/index";
import { graph34Monitoring } from "./34-monitoring/index";
import { graph35Testing } from "./35-testing/index";
import { graph36Scaling } from "./36-scaling/index";

// Register all 36 graphs
registerGraph(graph01HelloLanggraph);
registerGraph(graph02StateAndAnnotations);
registerGraph(graph03MultiTurnConversations);
registerGraph(graph04PromptTemplates);
registerGraph(graph05FewShotPrompting);
registerGraph(graph06TemplateComposition);
registerGraph(graph07StructuredOutput);
registerGraph(graph08PuttingItTogether);
registerGraph(graph09ThreadPersistence);
registerGraph(graph10ContextManagement);
registerGraph(graph11EmbeddingsSimilarity);
registerGraph(graph12LongTermMemory);
registerGraph(graph13RagFundamentals);
registerGraph(graph14AdvancedRag);
registerGraph(graph15DefiningTools);
registerGraph(graph16ReactAgent);
registerGraph(graph17Multimodal);
registerGraph(graph18HumanInTheLoop);
registerGraph(graph19PromptChaining);
registerGraph(graph20Routing);
registerGraph(graph21Subgraphs);
registerGraph(graph22ParallelPatterns);
registerGraph(graph23OrchestratorWorker);
registerGraph(graph24EvaluatorOptimizer);
registerGraph(graph25HierarchicalTeams);
registerGraph(graph26GenerativeUiFundamentals);
registerGraph(graph27InteractiveGenerativeUi);
registerGraph(graph28HumanInTheLoopUi);
registerGraph(graph29LanggraphPlatformUi);
registerGraph(graph30DisplayIntents);
registerGraph(graph31InteractiveIntents);
registerGraph(graph32Guardrails);
registerGraph(graph33ErrorHandling);
registerGraph(graph34Monitoring);
registerGraph(graph35Testing);
registerGraph(graph36Scaling);

console.log("All 36 graphs registered successfully");
