import { registerGraph } from "../lib/registry";
import { learn01MyFirstGraphModule } from "./learn-01-my-first-graph/index";
import { learn02MyProcessorModule } from "./learn-02-my-processor/index";
import { learn03MyChatbot } from "./learn-03-my-chatbot/index";
import { learn04MyTemplateAssistant } from "./learn-04-my-template-assistant/index";
import { learn05MyFormattingAssistant } from "./learn-05-my-formatting-assistant/index";
import { learn06MyMultiModeAssistant } from "./learn-06-my-multi-mode-assistant/index";
import { learn07MyExtractor } from "./learn-07-my-extractor/index";
import { learn08MySwissArmyKnife } from "./learn-08-my-swiss-army-knife/index";
import { learn09MyMemoryTester } from "./learn-09-persistence/index";
import { learn10MyContextManager } from "./learn-10-context-management/index";
import { learn11MyExampleSelectorModule } from "./learn-11-my-example-selector/index";
import { learn12LongTermMemoryModule } from "./learn-12-long-term-memory/index";
import { learn13RAGFundamentalsModule } from "./learn-13-rag-fundamentals/index";
import { learn14AdvancedRAG } from "./learn-14-advanced-rag/index";
import { learn15MyToolKit } from "./learn-15-my-tool-kit/index";
import { learn16ReactAgent } from "./learn-16-react-agent/index";
import { learn17MyVisionAgent } from "./learn-17-my-vision-agent/index";
import { learn18MyApprovalFlow } from "./learn-18-my-approval-flow/index";
import { learn19MyPipeline } from "./learn-19-my-pipeline/index";
import { learn20Routing } from "./learn-20-routing/index";
import { learn21MyComposedSystem } from "./learn-21-my-composed-system/index";
import { learn22MyParallelProcessor } from "./learn-22-my-parallel-processor/index";
import { learn23MyResearchTeam } from "./learn-23-my-research-team/index";
import { learn24MyCodeImprover } from "./learn-24-my-code-improver/index";
import { learn25MyProductTeam } from "./learn-25-my-product-team/index";
import { learn26MyUiAssistant } from "./learn-26-my-ui-assistant/index";
import { learn27MyBookingAssistant } from "./learn-27-my-booking-assistant/index";
import { learn28MyApprovalUi } from "./learn-28-my-approval-ui/index";
import { learn29MyPlatformGraph } from "./learn-29-my-platform-graph/index";
import { learn30MyWeatherAssistant } from "./learn-30-my-weather-assistant/index";
import { learn31MyTradingAssistant } from "./learn-31-my-trading-assistant/index";
import { learn32MySafeAgent } from "./learn-32-my-safe-agent/index";
import { learn33MyResilientAgent } from "./learn-33-my-resilient-agent/index";
import { learn34MyObservableAgent } from "./learn-34-my-observable-agent/index";
import { learn35MyTestedAgent } from "./learn-35-my-tested-agent/index";
import { learn36MyProductionAgent } from "./learn-36-my-production-agent/index";

// Register all 36 graphs
registerGraph(learn01MyFirstGraphModule);
registerGraph(learn02MyProcessorModule);
registerGraph(learn03MyChatbot);
registerGraph(learn04MyTemplateAssistant);
registerGraph(learn05MyFormattingAssistant);
registerGraph(learn06MyMultiModeAssistant);
registerGraph(learn07MyExtractor);
registerGraph(learn08MySwissArmyKnife);
registerGraph(learn09MyMemoryTester);
registerGraph(learn10MyContextManager);
registerGraph(learn11MyExampleSelectorModule);
registerGraph(learn12LongTermMemoryModule);
registerGraph(learn13RAGFundamentalsModule);
registerGraph(learn14AdvancedRAG);
registerGraph(learn15MyToolKit);
registerGraph(learn16ReactAgent);
registerGraph(learn17MyVisionAgent);
registerGraph(learn18MyApprovalFlow);
registerGraph(learn19MyPipeline);
registerGraph(learn20Routing);
registerGraph(learn21MyComposedSystem);
registerGraph(learn22MyParallelProcessor);
registerGraph(learn23MyResearchTeam);
registerGraph(learn24MyCodeImprover);
registerGraph(learn25MyProductTeam);
registerGraph(learn26MyUiAssistant);
registerGraph(learn27MyBookingAssistant);
registerGraph(learn28MyApprovalUi);
registerGraph(learn29MyPlatformGraph);
registerGraph(learn30MyWeatherAssistant);
registerGraph(learn31MyTradingAssistant);
registerGraph(learn32MySafeAgent);
registerGraph(learn33MyResilientAgent);
registerGraph(learn34MyObservableAgent);
registerGraph(learn35MyTestedAgent);
registerGraph(learn36MyProductionAgent);

console.log("All 36 graphs registered successfully");
